include $(DBG_ROOT_PATH)/build/build.mk
include $(DBG_DRIVERS_PATH)/drivers.mk

obj-$(CONFIG_LIDBG_PM)	+= lidbg_pm.o
obj-$(CONFIG_LIDBG_PM)	+= lidbg_powerkey.o
obj-$(CONFIG_SUSPEND_UNAIRPLANEMODE)	+= lidbg_rmtctrl.o


