include $(DBG_ROOT_PATH)/build/build.mk
include $(DBG_WORK_PATH)/$(DBG_SOC)/drivers.mk

obj-m	+= lidbg_videoin.o
lidbg_videoin-objs := lidbg_videoin_main.o tw9912.o TC358746XBG.o i2c_io.o video_init_config.o
#lidbg_videoin-objs := hello.o


