include $(DBG_ROOT_PATH)/build/build.mk
include $(DBG_DRIVERS_PATH)/drivers.mk

obj-$(CONFIG_FM1388)	+= lidbg_i2c_fm1388.o
obj-$(CONFIG_FM1388)	+= lidbg_spi_fm1388.o

#install ./fm1388_fw/*.dat ~/Android/V2.0_A20/android/out/target/product/sugar-cubietruck/system/etc/firmware/
