include $(DBG_ROOT_PATH)/build/build.mk
include $(DBG_DRIVERS_PATH)/drivers.mk

obj-$(CONFIG_MSM8226_DEVICE)	+= lidbg_devices.o
lidbg_devices-objs := misc_devices.o  ad.o button.o temp.o led.o sound_det.o

