include $(DBG_BOOTLOADER_DIR)/flyaudio/soc/$(DBG_SOC)/rules.mk

obj-y += bootloader_target_rk3x88.o
obj-y += fly_interface.o
obj-y += adc_func.o
obj-y += fb_func.o
obj-y += gpio_func.o
obj-y += ptn_func.o
