#include $(DBG_DRIVERS_PATH)/config_$(DBG_SOC)
include $(DBG_ROOT_PATH)/build/build.mk
include $(DBG_DRIVERS_PATH)/drivers.mk

obj-y	:= acc/ bp_msg/ devices/ drivers_dbg/ fastboot/ suspend_monitor/ gps/ touchscreen/ videoin/ monkey/ hal/ interface/ misc_devices/ powermanager/ dsi83/ lpc/ saf7741/  flysemdriver/ drivers_loader/ misc/ flyparameter/ bx5b3a/ pipe/ tw9992/ ad/ temp/ button/ update_gpt/ tef6638/ 


