include $(DBG_ROOT_PATH)/build/build.mk
include $(DBG_DRIVERS_PATH)/drivers.mk
include $(DBG_DRIVERS_PATH)/config_$(DBG_SOC)

obj-y	:= acc/ bp_msg/ devices/ example/ fastboot/ suspend_monitor/ gps/ touchscreen/ videoin/ monkey/ hal/
