include $(DBG_ROOT_PATH)/build/build.mk
include $(DBG_WORK_PATH)/$(DBG_SOC)/drivers.mk

#obj-m	+= lidbg_ts_probe.o
#obj-m	+= ft5x06_ts.o
#obj-m	+= ft5x06_ts_sku7.o
#obj-m	+= tcc_ts_focaltech.o
#obj-m	+= gt811.o
#obj-m	+= lidbg_ts_to_recov.o
#obj-m	+= gt801.o
#obj-m	+= gt80x_update.o
#obj-m	+= gt911.o
#obj-m += gt910new.o
#gt910new-objs :=gt910fm_update.o gt910.o 

