LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_SRC_FILES:= \
	main.c

#LOCAL_C_INCLUDES:= $(LOCAL_PATH)/src ../exfat/libexfat
LOCAL_CFLAGS:= -O2 -g -W -Wall -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H
LOCAL_MODULE_PATH := $(DBG_OUT_PATH)
LOCAL_MODULE:= fsck.exfat
LOCAL_MODULE_TAGS:=eng
LOCAL_SYSTEM_SHARED_LIBRARIES:= libc
LOCAL_STATIC_LIBRARIES:= libexfat

include $(BUILD_EXECUTABLE)
