ls /dev/ttyUSB* 
date > ~/minicom_log/ttyUSB0.txt
date > ~/minicom_log/ttyUSB1.txt
date > ~/minicom_log/ttyUSB2.txt
date > ~/minicom_log/ttyUSB3.txt
date > ~/minicom_log/ttyUSB4.txt
date > ~/minicom_log/ttyUSB5.txt
date > ~/minicom_log/ttyUSB6.txt
date > ~/minicom_log/ttyUSB7.txt
date > ~/minicom_log/ttyUSB8.txt
date > ~/minicom_log/ttyUSB9.txt
date > ~/minicom_log/ttyUSB10.txt
date > ~/minicom_log/ttyUSB11.txt
date > ~/minicom_log/ttyUSB12.txt
date > ~/minicom_log/ttyUSB13.txt
date > ~/minicom_log/ttyUSB14.txt
date > ~/minicom_log/ttyUSB15.txt
date > ~/minicom_log/ttyUSB16.txt
date > ~/minicom_log/ttyUSB17.txt
date > ~/minicom_log/ttyUSB18.txt
date > ~/minicom_log/ttyUSB19.txt
date > ~/minicom_log/ttyUSB20.txt
