
include $(DBG_BOOTLOADER_DIR)/flyaudio/common/rules.mk

obj-y += dsi83.o
obj-y += ctp_func.o
obj-y += flyaboot.o
obj-y += flykey.o
obj-y += flymeg.o
obj-y += showlogo.o
obj-y += lpc_i2c.o
obj-y += flyfbcon.o
obj-y += i2c_gpio.o
