
include $(DBG_SYSTEM_DIR)/uboot/flyaudio/common/rules.mk

obj-y += ctp_func.o
obj-y += flyaboot.o
obj-y += flykey.o
obj-y += flymeg.o
obj-y += showlogo.o
obj-y += i2c_screen.o
obj-y += flyfbcon.o
obj-y += i2c_gpio.o
